# Documentacion do aplicativo Portal (Apache 2.4)
ServerName localhost

DirectoryIndex index.php index.html

<Directory /var/www/html/portal_wct>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
